# Set update schedule for GitHub Actions, Go modules, Python (uv) dependencies, and container images

version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "weekly"

- package-ecosystem: "gomod"
  directory: "/fulfillment-service"
  schedule:
    # Check for updates to Go modules every week
    interval: "weekly"
  groups:
    fulfillment-service-go-dependencies:
      patterns:
        - "*"
  commit-message:
    prefix: "NO-ISSUE"

- package-ecosystem: "gomod"
  directories:
    - "/osac-operator"
    - "/osac-operator/api"
  schedule:
    # Check for updates to Go modules every week
    interval: "weekly"
  groups:
    osac-operator-go-dependencies:
      patterns:
        - "*"
  commit-message:
    prefix: "NO-ISSUE"

- package-ecosystem: "uv"
  directory: "/osac-aap"
  schedule:
    # Check for updates to Python (uv) dependencies every week
    interval: "weekly"
  groups:
    osac-aap-python-dependencies:
      patterns:
        - "*"
  commit-message:
    prefix: "NO-ISSUE"

- package-ecosystem: "docker"
  directory: "/fulfillment-service"
  schedule:
    # Check for updates to container base images every week
    interval: "weekly"
  groups:
    fulfillment-service-container-images:
      patterns:
        - "*"
  commit-message:
    prefix: "NO-ISSUE"

- package-ecosystem: "docker"
  directory: "/osac-operator"
  schedule:
    # Check for updates to container base images every week
    interval: "weekly"
  groups:
    osac-operator-container-images:
      patterns:
        - "*"
  commit-message:
    prefix: "NO-ISSUE"
